language: "ko-KR"  # 리뷰 결과를 한국어로 출력

tone_instructions: |
  코드 리뷰 시 친절하고 건설적인 의견을 제공하세요.
  코드 품질, 성능, 보안, 유지보수성에 집중해서 피드백을 남겨주세요.

reviews:
  profile: "chill"            # 리뷰 스타일: chill(부드럽게), strict(엄격하게) 등 선택 가능
  high_level_summary: true    # 변경사항 요약 활성화
  review_status: true         # 리뷰 상태 표시
  auto_review:
    enabled: true             # 자동 코드리뷰 활성화
    drafts: false             # Draft PR은 리뷰하지 않음
  path_instructions:
    - path: "src/api/**/*.ts"
      instructions: |
        API 코드 리뷰 시 다음 사항을 중점적으로 확인하세요:
        - 에러 핸들링이 적절한지
        - 입력값 검증이 충분한지
        - 타입이 명확하게 지정되어 있는지

    - path: "src/components/**/*.tsx"
      instructions: |
        React 컴포넌트 리뷰 시 다음을 확인하세요:
        - 불필요한 리렌더링이 발생하지 않는지
        - 접근성(a11y)이 잘 지켜지고 있는지
        - props 타입이 명확한지

knowledge_base:
  web_search:
    enabled: true             # 필요시 웹 검색 기반 지식 활용

chat:
  enabled: true               # PR에서 AI 챗 기능 활성화
  auto_reply: true            # 질문 시 자동 응답

